version: '3.7'

services:
  app_server:
    image: nickzylstra/nickzylstra-com:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    command: npm run start:docker
  nginx:
    restart: unless-stopped
    volumes:
      - ./deployData/nginx:/etc/nginx/conf.d
      - ./deployData/certbot/conf:/etc/letsencrypt
      - ./deployData/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    restart: unless-stopped
    volumes:
      - ./deployData/certbot/conf:/etc/letsencrypt
      - ./deployData/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"