version: '3.7'

services:
  app_server:
    build: .
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: npm run start:docker:development