version: '3.7'

services:
  postgres_db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
  app_server:
    build: .
    volumes:
      - .:/app
    depends_on:
      - 'postgres_db'
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
      POSTGRES_HOST: postgres_db
    command: npm run start:docker:dev